"""
questionnaire.py — interactive entity profiling.

Because residency and overlay obligations depend on the entity, the tool asks a short set of
questions and writes a `pdpl.config.yaml` the scanner reuses on every run. This is the step that
makes the output correct for a bank vs. a hospital vs. a private SaaS.
"""
from __future__ import annotations
import sys
from .entity_profiles import ENTITY_TYPES, CLASSIFICATION, EntityProfile


def _ask_choice(prompt: str, options: dict, default: str) -> str:
    keys = list(options.keys())
    print("\n" + prompt)
    for i, k in enumerate(keys, 1):
        mark = " (default)" if k == default else ""
        print(f"  {i}. {k} — {options[k]}{mark}")
    raw = input(f"Choose 1-{len(keys)} [{keys.index(default)+1}]: ").strip()
    if not raw:
        return default
    try:
        idx = int(raw) - 1
        if 0 <= idx < len(keys):
            return keys[idx]
    except ValueError:
        pass
    return default


def _ask_yn(prompt: str, default: bool = False) -> bool:
    d = "Y/n" if default else "y/N"
    raw = input(f"{prompt} [{d}]: ").strip().lower()
    if not raw:
        return default
    return raw in ("y", "yes", "1", "true")


def run_questionnaire() -> EntityProfile:
    print("=" * 64)
    print("PDPL Scanner — entity profile")
    print("Answers tune residency rules and which obligations apply.")
    print("=" * 64)

    etype = _ask_choice("What type of entity owns this system?", ENTITY_TYPES, "private_general")
    classification = _ask_choice(
        "Highest NDMO data classification this system handles?",
        CLASSIFICATION, "confidential")

    print("\nA few yes/no questions:")
    is_public = _ask_yn("Is this a public/government entity?", etype == "government")
    is_foreign = _ask_yn("Is the controller located outside KSA, processing data of people in KSA?", False)
    sensitive = _ask_yn("Does it process sensitive data (health, biometric, genetic, credit, criminal)?",
                        etype in ("health", "financial"))
    children = _ask_yn("Does it process data of children / those lacking legal capacity?", False)
    cross_border = _ask_yn("Does any personal data leave the Kingdom (cloud, SaaS, third parties)?", False)
    large_scale = _ask_yn("Is processing large-scale (high volume of data subjects)?", False)
    uses_ai = _ask_yn("Does it use AI/ML on personal data?", False)

    profile = EntityProfile(
        type=etype, is_public_entity=is_public, is_foreign_entity=is_foreign,
        processes_sensitive_data=sensitive, processes_children_data=children,
        cross_border_transfers=cross_border, large_scale_processing=large_scale,
        uses_ai_on_personal_data=uses_ai, data_classification=classification,
    )

    print("\n" + "-" * 64)
    print("Derived posture:")
    print(f"  Residency:            {profile.residency}")
    print(f"  Regulator overlays:   {', '.join(profile.overlays) or 'none (PDPL base)'}")
    print(f"  DPO required:         {profile.dpo_required}")
    print(f"  Registration:         {profile.registration_required}")
    print(f"  DPIA required:        {profile.dpia_required}")
    print("-" * 64)
    return profile


def profile_to_config(profile: EntityProfile, paths=None, exclude=None) -> str:
    paths = paths or ["src"]
    exclude = exclude or ["tests", "node_modules", "dist", "build"]
    lines = [
        "# PDPL Scanner configuration",
        "# Generated by `pdpl-scan init`. Commit this so every scan uses the same entity profile.",
        "entity:",
        f"  type: {profile.type}                 # {ENTITY_TYPES[profile.type]}",
        f"  data_classification: {profile.data_classification}   # top_secret | secret | confidential | public",
        f"  is_public_entity: {str(profile.is_public_entity).lower()}",
        f"  is_foreign_entity: {str(profile.is_foreign_entity).lower()}",
        f"  processes_sensitive_data: {str(profile.processes_sensitive_data).lower()}",
        f"  processes_children_data: {str(profile.processes_children_data).lower()}",
        f"  cross_border_transfers: {str(profile.cross_border_transfers).lower()}",
        f"  large_scale_processing: {str(profile.large_scale_processing).lower()}",
        f"  uses_ai_on_personal_data: {str(profile.uses_ai_on_personal_data).lower()}",
        "scan:",
        "  paths: [" + ", ".join(f'"{p}"' for p in paths) + "]",
        "  exclude: [" + ", ".join(f'"{e}"' for e in exclude) + "]",
        "gate:",
        "  fail_on: [critical]      # severities that fail the build",
        "  weights: { critical: 25, high: 10, medium: 4, low: 1 }",
    ]
    return "\n".join(lines) + "\n"
